### ISSUE TITLE
Prepare for Store Release

### ISSUE THREAD

**Issue by kunwarsahni01** [purduesigbots/pros-vsc#10]
Need to follow VS Extension Store Rules (cannot have svgs). See more [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by kunwarsahni01** [comment]
Will also need a CLI release before first extension release.

**Comment by WillXuCodes** [comment]
Other than these 2 things to do before store release, what else is there to do in terms of rules?

**Comment by kunwarsahni01** [comment]
Need to setup README, CHANGELOG, LICENSE see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration).

**Comment by WillXuCodes** [comment]
> Need to setup README, CHANGELOG, LICENSE see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration).

Might be able to take on some of these. 👍

**Comment by kunwarsahni01** [comment]
Mostly setup, need to fill out README, [check out store branch.](https://github.com/purduesigbots/pros-vsc/tree/feature/store-release)
