### ISSUE TITLE
🐛Pros having trouble installing CLI and Toolchain on Windows

### ISSUE THREAD

**Issue by Anonymas-Doge** [purduesigbots/pros-vsc#195]
#### Bug Description

Whenever I try to install PROS it says the installation failed

#### Platform

Windows 10 (school-issued laptop, command prompt is blocked)

#### Steps to reproduce

1. Press install Pros in side bar
2. When Pros says CLI and toolcahin are out of date or not installed press install

#### Additional Information

![image](https://github.com/purduesigbots/pros-vsc/assets/66092823/1b8a60b9-0ee9-44c3-8ab2-b9777341ad4d)

**Comment by AndrewLuGit** [comment]
If possible, could you go to `%appdata%\Code\User\globalStorage\sigbots.pros\logs` and send the log file for when the installation fails?

**Comment by Anonymas-Doge** [comment]
[PROS_Extension_log_2023-10-17T15-06-53.303Z.txt](https://github.com/purduesigbots/pros-vsc/files/12936529/PROS_Extension_log_2023-10-17T15-06-53.303Z.txt)

**Comment by AndrewLuGit** [comment]
I think the fact that command prompt is blocked on your computer is preventing the VSCode extension from running CLI and toolchain commands. I don't think there's anything we can do on our side to fix that.
