### ISSUE TITLE
Welcome View

### ISSUE THREAD

**Issue by kunwarsahni01** [purduesigbots/pros-vsc#2]
Current Status of the Welcome View:
![image](https://user-images.githubusercontent.com/22580992/118363027-73d8ad80-b560-11eb-87fa-36b9e521a9f1.png)
1. Logo needs to be changed to the SVG version
2. Buttons for present on startup and analytics need to be added
3. CLI and Extension Version handlers need to be added

**Comment by WillXuCodes** [comment]
Note: Logo can't be SVG now as per #10

**Comment by baylessj** [comment]
Beta version in #18 

Future improvements from discord convo:

- [ ] Sticky Sidebar, scroll the middle content only
- [ ] Quick Start buttons for new project and open project on sidebar
- [ ] CLI on PATH detection + install prompt

**Comment by kunwarsahni01** [comment]
This was completed.
