### ISSUE TITLE
Setting upload slot uses string instead of int

### ISSUE THREAD

**Issue by Sleuth56** [purduesigbots/pros-vsc#20]
When a user selects a slot to upload to using the GUI editor it puts the number in the config as a string instead of an int like it's supposed to be. 

https://github.com/purduesigbots/pros-cli/pull/128

**Comment by baylessj** [comment]
It sounds like this one has hit a number of people in Discord as well, this will likely be a pretty major problem for our users. I'll try to get this one taken care of ASAP.

**Comment by Ynng** [comment]
bump, just experienced the same issue
