### ISSUE TITLE
🐛PROS CLI and TOOLCHAIN issue, I do not know how to fix it. 🐛 please send help.

### ISSUE THREAD

**Issue by lizards777** [purduesigbots/pros-vsc#206]
#### Bug Description  
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/f8dfb9c9-ae46-43a5-87c7-ca610659f607)

#### Steps to reproduce

i dont know how to fix

apparently, the CLI and TOOLCHAIN are outdated or just not working in general.

**Comment by Rocky14683** [comment]
You are probably not on PROS integrated terminal.

**Comment by lizards777** [comment]
i think i am on it
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/b358c09c-ae64-415f-bf88-a0d0c2add9a4)

**Comment by lizards777** [comment]
pls help

**Comment by lizards777** [comment]
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/ec4996a7-4c9b-4337-98da-9bdfee26639d)
I am getting this problem.
Then when I press "Install now!", it gives me the same thing as before.
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/770cd3ec-ecb8-4a92-b24c-996a79e17de2)

**Comment by AndrewLuGit** [comment]
Could you go to `%appdata%\Code\User\globalStorage\sigbots.pros\logs` and send us the log file for when the installation fails?

**Comment by lizards777** [comment]
[PROS_Extension_log_2024-02-02T17-33-08.647Z.txt](https://github.com/purduesigbots/pros-vsc/files/14143515/PROS_Extension_log_2024-02-02T17-33-08.647Z.txt)

**Comment by lizards777** [comment]
> Could you go to `%appdata%\Code\User\globalStorage\sigbots.pros\logs` and send us the log file for when the installation fails?

[PROS_Extension_log_2024-02-02T17-33-08.647Z.txt](https://github.com/purduesigbots/pros-vsc/files/14143532/PROS_Extension_log_2024-02-02T17-33-08.647Z.txt)

**Comment by AndrewLuGit** [comment]
Looks like the error is here:
```
OneClick | 2024-02-02T17:38:04.248Z | ERROR :: Error: Command failed: pros c --help --machine-output 
This version of c:\Users\ecrro\AppData\Roaming\Code\User\globalStorage\sigbots.pros\install\pros-cli-windows\pros.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
What version of Windows are you running? And if it's Windows 10/11, could you find your device specifications and check what type of processor your computer has?

**Comment by lizards777** [comment]
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/1b51a049-1375-4bd3-9a8e-60b1739bc7c9)
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/d42f56ab-fef1-46b8-b366-7fdf65f695fb)
I don't know, I should have all the specs to run the PROS.

**Comment by AndrewLuGit** [comment]
From what I could find online, it might also be due to a corrupted download. Maybe try uninstalling PROS and then reinstalling.

**Comment by lizards777** [comment]
> From what I could find online, it might also be due to a corrupted download. Maybe try uninstalling PROS and then reinstalling.
![image](https://github.com/purduesigbots/pros-vsc/assets/148751549/b267eec1-773e-41db-89cd-1ff961fdd19a)
I reinstalled the PROS along with the default CLI and Toolchain files and am still getting the same error.
Also, I have tried downloading the files manually which didn't work. We also tried factory resetting and trying to download everything again on multiple computers but kept getting the same error.

**Comment by lizards777** [comment]
All of the computers were windows 10 and Lenovo laptops. I don't know if that changes anything.

**Comment by AndrewLuGit** [comment]
Maybe try running the Windows program compatibility troubleshooter https://support.microsoft.com/en-us/windows/make-older-apps-or-programs-compatible-with-windows-783d6dd7-b439-bdb0-0490-54eea0f45938 If that doesn't work, I'm not sure what else you can do.

**Comment by AndrewLuGit** [comment]
I think the download links must have broken somehow, I am also getting this on my computer

**Comment by lizards777** [comment]
> I think the download links must have broken somehow, I am also getting this on my computer

Yeah, it is weird because I have tried with multiple computers and windows 11 and 10 computers and the default links that the PROS extension installs keep repeating the same error.

**Comment by noam987** [comment]
Something broke yesterday. We are looking into it

**Comment by lizards777** [comment]
OMG THEY FIXED IT. THE PROS V0.7.1 UPDATE FIXED THE BUG. THANK YOU SO MUCH!!!!

**Comment by AndrewLuGit** [comment]
I’m glad that worked. Thank you for bringing this to our attention as well!
