### ISSUE TITLE
🐛 Open Source Marketplace Extension Out Of Date

### ISSUE THREAD

**Issue by SizzinSeal** [purduesigbots/pros-vsc#221]
#### Bug Description

On Code - OSS and VS Codium, the PROS extension is out of date

#### Platform

Hardware: N/A
Software: VS Codium / Code - OSS

#### Steps to reproduce

1. VS Codium, or Code - OSS
2. Observe pros extension version in marketplace (v0.5.0)

**Comment by AndrewLuGit** [comment]
The extension has been updated to the latest version on open-vsx. In the future, we will update open-vsx whenever we release a new version of the extension.
