### ISSUE TITLE
PROS Menu Buttons Don't Show

### ISSUE THREAD

**Issue by Rohan-Raman** [purduesigbots/pros-vsc#23]
The menu options shown in the README.md file do not show up on my installation. This is Debian, running the latest version of Visual Studio Code.
![image](https://user-images.githubusercontent.com/84888741/133914438-8897c21d-8c7b-4b52-98dc-086c98899a81.png)
How do I fix this? I believe that pros and prosv5 are on path and running --version displays "version 3.2.2".

Thanks for any help.

**Comment by BrenekH** [comment]
You're talking about these buttons correct?

![PROS Sidebar Menu](https://user-images.githubusercontent.com/22580992/123257423-22590200-d4c0-11eb-9fda-ce33148d46b6.png)

**Comment by Rohan-Raman** [comment]
Yes, should’ve specified

**Comment by HotelCalifornia** [comment]
do they show up if you add a pros project to the workspace?

**Comment by Rohan-Raman** [comment]
Oh, I get it. In order for the buttons to show up, you have to be in an actual folder (not just the welcome page). Opening vscode as a directory has the buttons show up. Thanks!

**Comment by HotelCalifornia** [comment]
yeah, those are project specific options and don't make much sense to show when there's no project around
