### ISSUE TITLE
Nothing in the extension sidebar

### ISSUE THREAD

**Issue by BenBenny11** [purduesigbots/pros-vsc#30]
When I clicked the extension icon after installing the PROS extension for VEX V5, nothing came up.
![image](https://user-images.githubusercontent.com/50433844/145039645-d8f376cd-e74c-4757-ab14-0afaa7b8b66d.png)

I also installed PROS-cli using pip install --upgrade pros-cli

**Comment by kunwarsahni01** [comment]
You need to open a PROS Project first for the extension to activate.

**Comment by BenBenny11** [comment]
> 

How do I create a PROS project

**Comment by kunwarsahni01** [comment]
Check out our [documentation](https://pros.cs.purdue.edu/v5/cli/conductor.html#common-tasks).

**Comment by BenBenny11** [comment]
> Check out our [documentation](https://pros.cs.purdue.edu/v5/cli/conductor.html#common-tasks).

How do I open the PROS file after running pros conduct new-project ./Top-5-At-Worlds

**Comment by kunwarsahni01** [comment]
You can open your PROS project folder using the open folder button from inside the file menu in VSCode.
