### ISSUE TITLE
Upload PROS to Open VSX registry

### ISSUE THREAD

**Issue by CyborgRyno603YT** [purduesigbots/pros-vsc#54]
This would help because PROS is useful to people and some users on Chromebook can't use the Linux mode and are forced towards things like Gitpod, which only allows extensions from the Open VSX registry.

**Comment by HotelCalifornia** [comment]
never heard of this registry but we can look into this when the plugin is in a more stable state

**Comment by kunwarsahni01** [comment]
Requested for the extension to be added https://github.com/open-vsx/publish-extensions/pull/606.
