### ISSUE TITLE
Add Settings View

### ISSUE THREAD

**Issue by kunwarsahni01** [purduesigbots/pros-vsc#8]
Should allow user to change settings associated with the extension.

**Comment by baylessj** [comment]
What settings do we have in mind for the extension currently? I don't know of any configurable options for the extension that we need right now.

**Comment by kunwarsahni01** [comment]
Some configurable options could be: enable/disable google analytics, show welcome page on startup, customize quick action. To clarify this shouldn't be a "settings view", this should just be exposing these settings to vscode's settings view.

**Comment by baylessj** [comment]
Closed by #15
